/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RelatorioFrame.java
 *
 * Created on 27/03/2013, 10:20:16
 */
package sip.relatoriosarquivo;

import sip.menulogin.Menu;
import sip.acessobd.AcessoBD;
import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author jallisson
 */
public class RelatorioTriagemPoluicaoFrame extends javax.swing.JInternalFrame {

   
      private JDateChooser jdcDataInicial;
      private JDateChooser jdcDataFinal;
    /** Creates new form RelatorioFrame */
    public RelatorioTriagemPoluicaoFrame() {
        initComponents();
        formataData();
        fechando();
    }
    
    private void fechando() {  
          this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);  
          
        this.addInternalFrameListener(new InternalFrameAdapter(){  
            @Override
                public void internalFrameClosing(InternalFrameEvent e) {  
                   int result = JOptionPane.showConfirmDialog(null,"Deseja sair?","Sair",JOptionPane.YES_NO_OPTION);  
                     
                   if (result == JOptionPane.YES_OPTION) {
                       RelatorioTriagemPoluicaoFrame.this.dispose();
                       Menu.menuVisivel();
                    /*   if(tblItensAtendimento.getRowCount() < 1){
                            RegistraAtendimentoFrame.this.setVisible(false);  
                            RegistraAtendimentoFrame.this.dispose();   
                       }
                       else
                           JOptionPane.showMessageDialog(null, "Excluia todos os ítens do Atendimento!", "Aviso", JOptionPane.INFORMATION_MESSAGE); 
                    */
                   }       
              }  
            }
          );
       } 
    
    private void formataData(){
        
            jdcDataInicial = new JDateChooser("dd/MM/yyyy", "##/##/#####", '_');  
            jdcDataInicial.setBorder(new LineBorder(new Color(30, 144, 255), 1, false));  
            jdcDataInicial.setBackground(Color.WHITE);  
            jdcDataInicial.setBounds(255, 91, 87, 20);             
           
            jPanel3.add(jdcDataInicial);
            
            jdcDataFinal = new JDateChooser("dd/MM/yyyy", "##/##/#####", '_');  
            jdcDataFinal.setBorder(new LineBorder(new Color(30, 144, 255), 1, false));  
            jdcDataFinal.setBackground(Color.WHITE);  
            jdcDataFinal.setBounds(255, 91, 87, 20);             
           
            jPanel4.add(jdcDataFinal);         
                    
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        btnVisualizar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Titulos Emitidos Por Período\n\n");
        setPreferredSize(new java.awt.Dimension(350, 200));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        btnVisualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sip/imagem/printer.png"))); // NOI18N
        btnVisualizar.setText("Imprimir");
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(btnVisualizar, gridBagConstraints);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecione a Data"));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Inicio: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(jLabel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 66;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jPanel3, gridBagConstraints);

        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Fim: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 66;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jPanel4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jPanel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarActionPerformed
      AcessoBD acessoBd = new AcessoBD();   
        
      if (jdcDataInicial.getDate() == null){
            JOptionPane.showMessageDialog(this,"Informe a data Inicial","Erro",JOptionPane.INFORMATION_MESSAGE);
            jdcDataInicial.requestFocus();
        }else if (jdcDataFinal.getDate() == null){
            JOptionPane.showMessageDialog(this,"Informe a data Final","Erro",JOptionPane.INFORMATION_MESSAGE);
            jdcDataFinal.requestFocus();
        }else {
       try {
              //SimpleDateFormat dataFormatado = new SimpleDateFormat("dd/MM/yyyy");
             // Date dataInicial = dataFormatado.parse(jDateTeste.getDate().toString());
             // Date dataFinal = dataFormatado.parse(jDateFinal.getDate().toString());
            
            HashMap parametros = new HashMap();
            //parametros.put("CAMINHO_IMAGEM", System.getProperty("user.dir") + "\\imagem\\logoserf.jpg");
            //parametros.put("SUBREPORT_DIR", System.getProperty("user.dir") + "\\relatorios\\");
            parametros.put("DATA_INICIAL", jdcDataInicial.getDate()); //new Date("2011/07/01"));
            parametros.put("DATA_FINAL", jdcDataFinal.getDate()); //new Date("2011/07/31"));
            
           JasperPrint jp = JasperFillManager.fillReport(System.getProperty("user.dir") + "\\relatorios\\relatorioTriagemPoluicao.jasper", parametros, acessoBd.conectar());
            this.dispose();
            JasperViewer.viewReport(jp, false);
       //} catch (ParseException ex) {
          //  ex.printStackTrace();
        }catch (JRException ex) {
            Logger.getLogger(RelatorioTriagemPoluicaoFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
      }
    }//GEN-LAST:event_btnVisualizarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVisualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the loteEmissao
     */




}
