/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RelatorioFrame.java
 *
 * Created on 27/03/2013, 10:20:16
 */
package sip.relatorio;

import sip.menulogin.Menu;
import sip.acessobd.AcessoBD;
import sip.processo.Processo;
import sip.processo.ProcessoFrame;
import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.awt.Dimension;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author jallisson
 */
public class RelatorioMovimentoProcessoFrame extends javax.swing.JInternalFrame {

   
    private JDateChooser jdcDataInicial;
    private Processo processo;

    /** Creates new form RelatorioFrame */
    public RelatorioMovimentoProcessoFrame() {
        initComponents();
        formataData();
        fechando();
    }
    
    private void fechando() {  
          this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);  
          
        this.addInternalFrameListener(  
            new InternalFrameAdapter(){  
            @Override
                public void internalFrameClosing(InternalFrameEvent e) {  
                   int result = JOptionPane.showConfirmDialog(null,"Deseja sair?","Sair",JOptionPane.YES_NO_OPTION);  
                     
                   if (result == JOptionPane.YES_OPTION) {
                       RelatorioMovimentoProcessoFrame.this.dispose();
                       Menu.menuVisivel();
                    /*   if(tblItensAtendimento.getRowCount() < 1){
                            RegistraAtendimentoFrame.this.setVisible(false);  
                            RegistraAtendimentoFrame.this.dispose();   
                       }
                       else
                           JOptionPane.showMessageDialog(null, "Excluia todos os ítens do Atendimento!", "Aviso", JOptionPane.INFORMATION_MESSAGE); 
                    */
                   }       
              }  
            }
          );
       } 
    
    private void formataData(){
        
            jdcDataInicial = new JDateChooser("dd/MM/yyyy", "##/##/#####", '_');  
            jdcDataInicial.setBorder(new LineBorder(new Color(30, 144, 255), 1, false));  
            jdcDataInicial.setBackground(Color.WHITE);  
            jdcDataInicial.setBounds(255, 91, 87, 20);             
           
           // jPanel4.add(jdcDataInicial);
                    
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnSelecionaVenda = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ftfIdProcesso = new javax.swing.JFormattedTextField();
        btnVisualizar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Movimento Processo\n\n\n");
        setPreferredSize(new java.awt.Dimension(320, 230));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Id ou Numero", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel2.setLayout(new java.awt.GridBagLayout());

        btnSelecionaVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sip/imagem/lupa_16x16.png"))); // NOI18N
        btnSelecionaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionaVendaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -30;
        gridBagConstraints.ipady = -5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(btnSelecionaVenda, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText("Id / Numero");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jLabel3, gridBagConstraints);

        try {
            ftfIdProcesso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfIdProcesso.setFont(new java.awt.Font("Tahoma", 1, 12));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 50;
        jPanel2.add(ftfIdProcesso, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jPanel2, gridBagConstraints);

        btnVisualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sip/imagem/printer.png"))); // NOI18N
        btnVisualizar.setText("Imprimir");
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(btnVisualizar, gridBagConstraints);

        jPanel3.setBackground(java.awt.SystemColor.inactiveCaption);
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sip/imagemsip/Movimento_64x64.png"))); // NOI18N
        jPanel3.add(jLabel1, new java.awt.GridBagConstraints());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sip/imagemsip/documento_64x64.png"))); // NOI18N
        jPanel3.add(jLabel2, new java.awt.GridBagConstraints());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sip/imagemsip/Movimento_64x64.png"))); // NOI18N
        jPanel3.add(jLabel4, new java.awt.GridBagConstraints());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sip/imagemsip/documento_64x64.png"))); // NOI18N
        jPanel3.add(jLabel5, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(jPanel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarActionPerformed
      AcessoBD acessoBd = new AcessoBD();   
        
        if (ftfIdProcesso.getValue() == null){
            JOptionPane.showMessageDialog(this,"Informe o id ou numero do Processo","Erro",JOptionPane.INFORMATION_MESSAGE);
            ftfIdProcesso.requestFocus();
        }else {
            
             JOptionPane.showMessageDialog(this,"Aguarde Enquanto é gerado","Impressão",JOptionPane.INFORMATION_MESSAGE);

        try {
            
            HashMap parametros = new HashMap();
            
            if (getProcesso() == null) {
                parametros.put("NUM_PROCESSO",ftfIdProcesso.getValue());
            }else{
                parametros.put("ID_PROCESSO",ftfIdProcesso.getValue());
            }
            parametros.put("CAMINHO_IMAGEM", System.getProperty("user.dir") + "\\imagem\\logoprefeituranova.png");
            
            
            
            JasperPrint jp = JasperFillManager.fillReport(System.getProperty("user.dir") + "\\relatorios\\MovimentoProcesso.jasper", parametros, acessoBd.conectar());
            
            
            
            
            JasperViewer.viewReport(jp, false);
            //JasperPrintManager.printReport(jp, false); 
            //JasperPrintManager.printPage(jp,0,false); 
            this.dispose();
            Menu.menuVisivel();
            //JasperPrintManager.printReport(jp, false); 
            
        } catch (JRException ex) {
            Logger.getLogger(RelatorioMovimentoProcessoFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
     }   
    }//GEN-LAST:event_btnVisualizarActionPerformed

    private void btnSelecionaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionaVendaActionPerformed
        ProcessoFrame loteEmissao = new ProcessoFrame(this);
        loteEmissao.setVisible(true);
        this.getDesktopPane().add(loteEmissao);
        loteEmissao.toFront();
}//GEN-LAST:event_btnSelecionaVendaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelecionaVenda;
    private javax.swing.JButton btnVisualizar;
    private javax.swing.JFormattedTextField ftfIdProcesso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the loteEmissao
     */
    public Processo getProcesso() {
        return processo;
    }

    /**
     * @param loteEmissao the loteEmissao to set
     */
    public void setProcesso(Processo processo) {
        this.processo = processo;
         ftfIdProcesso.setValue((long)processo.getId());
         ftfIdProcesso.setEditable(true);
    }



}
