/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * RelatorioFrame.java
 *
 * Created on 27/03/2013, 10:20:16
 */
package sip.relatorio;

import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import sip.acessobd.AcessoBD;
import sip.analista.Analista;
import sip.analista.AnalistaBD;
import sip.analista.AnalistaFrame;

/**
 *
 * @author jallisson
 */
public class RelDenunciaData extends javax.swing.JInternalFrame {

    private Analista analista;
    private List<Analista> listAnalista;

    /**
     * Creates new form RelatorioFrame
     */
    public RelDenunciaData() {
        initComponents();
        // formataData();
    }

    private void centralizaJanelaRegVen(JInternalFrame internalFrame) {
        internalFrame.setLocation((this.getWidth() - internalFrame.getWidth()) / 36,
                (this.getHeight() - internalFrame.getHeight()) / 12);
    }

    private void formataData() {

        jDCDataInicio = new JDateChooser("dd/MM/yyyy", "##/##/#####", '_');
        jDCDataFim = new JDateChooser("dd/MM/yyyy", "##/##/#####", '_');

        jDCDataFim.setBorder(new LineBorder(new Color(30, 144, 255), 1, false));
        jDCDataFim.setBackground(Color.WHITE);
        jDCDataFim.setBounds(255, 91, 87, 20);

        jDCDataInicio.setBorder(new LineBorder(new Color(30, 144, 255), 1, false));
        jDCDataInicio.setBackground(Color.WHITE);
        jDCDataInicio.setBounds(255, 91, 87, 20);

    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jDCDataInicio = new com.toedter.calendar.JDateChooser();
        jDCDataFim = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnVisualizar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Denuncias por Data");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecione a Data"));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jDCDataInicio = new JDateChooser("dd/MM/yyyy", "##/##/#####", '_');
        jDCDataInicio.setBorder(new LineBorder(new Color(30, 144, 255), 1, false));
        jDCDataInicio.setBackground(Color.WHITE);
        jDCDataInicio.setBounds(255, 91, 87, 20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.insets = new java.awt.Insets(31, 4, 27, 0);
        jPanel2.add(jDCDataInicio, gridBagConstraints);

        jDCDataFim = new JDateChooser("dd/MM/yyyy", "##/##/#####", '_');

        jDCDataFim.setBorder(new LineBorder(new Color(30, 144, 255), 1, false));
        jDCDataFim.setBackground(Color.WHITE);
        jDCDataFim.setBounds(255, 91, 87, 20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 4, 0, 6);
        jPanel2.add(jDCDataFim, gridBagConstraints);

        jLabel1.setText("Fim:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Inicio:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jLabel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jPanel2, gridBagConstraints);

        btnVisualizar.setText("Confirmar");
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(btnVisualizar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarActionPerformed
        AcessoBD acessoBd = new AcessoBD();

        if (jDCDataInicio.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Informe a data Inicial", "Erro", JOptionPane.INFORMATION_MESSAGE);
            jDCDataInicio.requestFocus();
        } else if (jDCDataFim.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Informe a data Final", "Erro", JOptionPane.INFORMATION_MESSAGE);
            jDCDataFim.requestFocus();
        }  else {
             
     
            try {
                //SimpleDateFormat dataFormatado = new SimpleDateFormat("dd/MM/yyyy");
                // Date dataInicial = dataFormatado.parse(jDateTeste.getDate().toString());
                // Date dataFinal = dataFormatado.parse(jDateFinal.getDate().toString());

                HashMap parametros = new HashMap();
                parametros.put("DATA_INICIAL", jDCDataInicio.getDate()); //new Date("2011/07/01"));
                parametros.put("DATA_FINAL", jDCDataFim.getDate()); //new Date("2011/07/31"));
                

                JasperPrint jp = JasperFillManager.fillReport(System.getProperty("user.dir") + "\\relatorios\\listagemDenunciasData.jasper", parametros, acessoBd.conectar());
                this.dispose();
                JasperViewer.viewReport(jp, false);

                //} catch (ParseException ex) {
                //  ex.printStackTrace();
            } catch (JRException ex) {
                Logger.getLogger(RelDenunciaData.class.getName()).log(Level.SEVERE, null, ex);
            }
        } // TODO add your handling code here:*/


    }//GEN-LAST:event_btnVisualizarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVisualizar;
    private com.toedter.calendar.JDateChooser jDCDataFim;
    private com.toedter.calendar.JDateChooser jDCDataInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the cliente
     */
    public Analista getAnalista() {
        return analista;
    }

    /**
     * @param analista the cliente to set
     */
    public void setAnalista(Analista analista) {
        this.analista = analista;
        //txtNomeAnalista.setText(analista.getNome());
        //txtIdAnalista.setText(analista.getId().toString());

    }
}
