/*
 * ControleAcessosView.java
 *
 * Created on 12 de Setembro de 2008, 01:25
 */
package sip.utilitarios;

import bsh.ParseException;
import sip.menulogin.Menu;
import sip.bean.NivelAcesso;
import sip.util.Constantes;
import groovy.model.DefaultTableModel;
import java.beans.Beans;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author  Albert
 */
public class ControleAcessosView1 extends javax.swing.JFrame {

    private DefaultTableModel tableModel;
    private ListSelectionModel listModel;
    int modo;
    /** Creates new form ControleAcessosView */
    public ControleAcessosView1() {
       initComponents();
        if (!Beans.isDesignTime()) {
            entityManager.getTransaction().begin();
        }
   
    }
    
    private void autorizaBotaoRetirar(){
        if(tblInformacao.getSelectedRow() == -1 ){
          JOptionPane.showMessageDialog(this, "Selecine a tabela retirada de permissão!", "Tabela", JOptionPane.ERROR_MESSAGE);
            //btnRetirar.setEnabled(true);
        }  
    }
    
    private void salvar(){
          try {
        if(modo == Constantes.EXCLUIR){
        entityManager.getTransaction().commit();
        entityManager.getTransaction().begin();
        tblConceder.clearSelection();
        JOptionPane.showMessageDialog(this, "Módulo(s) Retirado com Sucesso!", "Retirada", JOptionPane.INFORMATION_MESSAGE);
        dispose();
        }else if(modo == Constantes.INCLUIR){
        entityManager.getTransaction().commit();
        entityManager.getTransaction().begin();
        tblConceder.clearSelection();
        JOptionPane.showMessageDialog(this, "Módulo(s) Concedido com Sucesso!", "Retirada", JOptionPane.INFORMATION_MESSAGE);
        dispose();
        Menu.menuVisivel();
        }
       
    } catch (Exception e) {
        e.printStackTrace();
        
    }
        
  }

    private void conceder(){
       try {
        NivelAcesso ne = new NivelAcesso();
        entityManager.persist(ne);
        int index = tblUsuario.getSelectedRow();
        ne.setIdUsuario(usuarioList.get(index).getId());
        ne.setNomeModulo(jTree1.getLastSelectedPathComponent().toString());
        nivelAcessoList.add(ne);
        modo = Constantes.INCLUIR;

    } catch (ArrayIndexOutOfBoundsException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Selecione a Tabela Módulos e o Usuario!", "Modulo", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }catch (NullPointerException e){
       e.printStackTrace();
       JOptionPane.showMessageDialog(this, "Selecione o módulo na tabela de módulos!", "Modulo", JOptionPane.INFORMATION_MESSAGE);
       this.dispose();
    }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("SipPU").createEntityManager();
        nivelAcessoQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT n FROM NivelAcesso n where n.id = 999999");
        usuarioQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT u FROM Usuario u");
        usuarioList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(usuarioQuery.getResultList());
        nivelAcessoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(nivelAcessoQuery.getResultList());
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DefaultMutableTreeNode pai = new DefaultMutableTreeNode("SIP");

        DefaultMutableTreeNode filho1 = new DefaultMutableTreeNode("Movimento");
        pai.add(filho1);
        DefaultMutableTreeNode neto1 = new DefaultMutableTreeNode("Usuario");
        filho1.add(neto1);

        DefaultMutableTreeNode filho7 = new DefaultMutableTreeNode("Protocolo");
        filho1.add(filho7);
        DefaultMutableTreeNode neto2 = new DefaultMutableTreeNode("Logradouro");
        filho7.add(neto2);
        DefaultMutableTreeNode neto3 = new DefaultMutableTreeNode("Bairro");
        filho7.add(neto3);
        DefaultMutableTreeNode neto4 = new DefaultMutableTreeNode("Cidade");
        filho7.add(neto4);
        DefaultMutableTreeNode neto5 = new DefaultMutableTreeNode("Atividade");
        filho7.add(neto5);
        DefaultMutableTreeNode neto6 = new DefaultMutableTreeNode("Requerente");
        filho7.add(neto6);
        DefaultMutableTreeNode neto7 = new DefaultMutableTreeNode("Analista");
        filho7.add(neto7);
        DefaultMutableTreeNode neto21 = new DefaultMutableTreeNode("Tipo Licença");
        filho7.add(neto21);

        DefaultMutableTreeNode filho6 = new DefaultMutableTreeNode("DENUNCIA");
        filho1.add(filho6);
        DefaultMutableTreeNode neto30 = new DefaultMutableTreeNode("Pessoa");
        filho6.add(neto30);
        DefaultMutableTreeNode neto31 = new DefaultMutableTreeNode("Natureza da Ocorrência");
        filho6.add(neto31);
        DefaultMutableTreeNode neto32 = new DefaultMutableTreeNode("Denuncia");
        filho6.add(neto32);
        DefaultMutableTreeNode neto33 = new DefaultMutableTreeNode("Resumo Triagem");
        filho6.add(neto33);
        DefaultMutableTreeNode neto34 = new DefaultMutableTreeNode("Triagem");
        filho6.add(neto34);

        DefaultMutableTreeNode filho2 = new DefaultMutableTreeNode("MOVIMENTO");
        pai.add(filho2);
        DefaultMutableTreeNode neto8 = new DefaultMutableTreeNode("Processo");
        filho2.add(neto8);
        DefaultMutableTreeNode filho3 = new DefaultMutableTreeNode("DMA");
        filho2.add(filho3);
        DefaultMutableTreeNode neto9 = new DefaultMutableTreeNode("Distribuicao DMA");
        filho3.add(neto9);
        DefaultMutableTreeNode neto10 = new DefaultMutableTreeNode("Emissão Licença");
        filho3.add(neto10);
        DefaultMutableTreeNode neto11 = new DefaultMutableTreeNode("Tipo Evento");
        filho3.add(neto11);
        DefaultMutableTreeNode neto27 = new DefaultMutableTreeNode("Local do Evento");
        filho3.add(neto27);
        DefaultMutableTreeNode neto12 = new DefaultMutableTreeNode("Autorização Eventos");
        filho3.add(neto12);
        DefaultMutableTreeNode neto19 = new DefaultMutableTreeNode("Lote Dma");
        filho3.add(neto19);
        DefaultMutableTreeNode neto20 = new DefaultMutableTreeNode("Movimento Dma");
        filho3.add(neto20);

        DefaultMutableTreeNode neto14 = new DefaultMutableTreeNode("Análise");
        filho2.add(neto14);
        DefaultMutableTreeNode neto15 = new DefaultMutableTreeNode("Jurídico");
        filho2.add(neto15);
        DefaultMutableTreeNode neto28 = new DefaultMutableTreeNode("Fiscalização");
        filho2.add(neto28);
        DefaultMutableTreeNode neto16 = new DefaultMutableTreeNode("Gabinete");
        filho2.add(neto16);
        DefaultMutableTreeNode neto17 = new DefaultMutableTreeNode("Tramitação");
        filho2.add(neto17);
        DefaultMutableTreeNode neto29 = new DefaultMutableTreeNode("Receita");
        filho2.add(neto29);

        DefaultMutableTreeNode filho4 = new DefaultMutableTreeNode("RELATORIOS");
        pai.add(filho4);
        DefaultMutableTreeNode neto18 = new DefaultMutableTreeNode("Movimento Processo");
        filho4.add(neto18);
        DefaultMutableTreeNode neto22 = new DefaultMutableTreeNode("Relatorio Triagem Poluição");
        filho4.add(neto22);
        DefaultMutableTreeNode neto23 = new DefaultMutableTreeNode("Relatorio Denuncia Data");
        filho4.add(neto23);
        DefaultMutableTreeNode neto24 = new DefaultMutableTreeNode("Relatorio Processo Analista Analise");
        filho4.add(neto24);
        DefaultMutableTreeNode neto25 = new DefaultMutableTreeNode("Relatorio Processo Não Baixado");
        filho4.add(neto25);
        DefaultMutableTreeNode filho5 = new DefaultMutableTreeNode("UTILITARIOS");
        pai.add(filho5);
        DefaultMutableTreeNode neto26 = new DefaultMutableTreeNode("Nivel de Acesso");
        filho5.add(neto18);
        jTree1 = new javax.swing.JTree(pai);
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUsuario = new javax.swing.JTable();
        btnConceder = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblConceder = new javax.swing.JTable();
        btnRetirar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblInformacao = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Controle de Acessos");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(850, 590));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 590));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTree1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tabela Módulos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jTree1.setToolTipText("Click no módulo duas vezes para conceder permissão!");
        jTree1.setEnabled(false);
        jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTree1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 330, 330));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tabela Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 11))); // NOI18N

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, usuarioList, tblUsuario);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${id}"));
        columnBinding.setColumnName("Idl");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${login}"));
        columnBinding.setColumnName("Login");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nome}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        tblUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuarioMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblUsuario);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 180));

        btnConceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sip/imagem/8436_32x32.png"))); // NOI18N
        btnConceder.setText("Conceder");
        btnConceder.setEnabled(false);
        btnConceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcederActionPerformed(evt);
            }
        });
        jPanel1.add(btnConceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, -1, 50));

        jScrollPane5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Módulos do Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 11))); // NOI18N
        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        tblConceder.setMaximumSize(new java.awt.Dimension(2147483647, 50));

        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, nivelAcessoList, tblConceder);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${id}"));
        columnBinding.setColumnName("Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idMonitor}"));
        columnBinding.setColumnName("Id Monitor");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nomeModulo}"));
        columnBinding.setColumnName("Nome Modulo");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane5.setViewportView(tblConceder);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 290, 340));

        btnRetirar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sip/imagem/8454_32x32.png"))); // NOI18N
        btnRetirar.setText("Retirar");
        btnRetirar.setEnabled(false);
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 110, 50));

        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tabela para retirada de permissão", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 11))); // NOI18N

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${selectedElement.nivelAcessoCollection}");
        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblUsuario, eLProperty, tblInformacao);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${id}"));
        columnBinding.setColumnName("Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idMonitor}"));
        columnBinding.setColumnName("Id Monitor");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nomeModulo}"));
        columnBinding.setColumnName("Nome Modulo");
        columnBinding.setColumnClass(String.class);
        jTableBinding.setSourceUnreadableValue(java.util.Collections.emptyList());
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane3.setViewportView(tblInformacao);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 290, 180));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sip/imagem/disk.png"))); // NOI18N
        jButton4.setText("Gravar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 550, 140, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 780, 590));

        bindingGroup.bind();

        setSize(new java.awt.Dimension(797, 642));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed
     try{
        autorizaBotaoRetirar();
        int index = tblUsuario.getSelectedRow();
        sip.bean.Usuario m = usuarioList.get(tblUsuario.convertRowIndexToModel(index));
        Collection<sip.bean.NivelAcesso> ns = m.getNivelAcessoCollection();
        int[] selected = tblInformacao.getSelectedRows();
        List<sip.bean.NivelAcesso> toRemove = new ArrayList<sip.bean.NivelAcesso>(selected.length);
        for (int idx = 0; idx < selected.length; idx++) {
            selected[idx] = tblInformacao.convertRowIndexToModel(selected[idx]);
            int count = 0;
            Iterator<sip.bean.NivelAcesso> iter = ns.iterator();
            while (count++ < selected[idx]) {
                iter.next();
            }
                sip.bean.NivelAcesso n = iter.next();
            toRemove.add(n);
            entityManager.remove(n);
           
        }
        ns.removeAll(toRemove);
        tblUsuario.clearSelection();
        tblUsuario.setRowSelectionInterval(index, index);
        modo = Constantes.EXCLUIR;
     }catch(ArrayIndexOutOfBoundsException e){
         e.printStackTrace();
       JOptionPane.showMessageDialog(this, "Selecione o Digitador na tabela de monitores!", "Digitador", JOptionPane.INFORMATION_MESSAGE);
     }
        
}//GEN-LAST:event_btnRetirarActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
   
    salvar();  
}//GEN-LAST:event_jButton4ActionPerformed

private void jTree1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MouseClicked
        if (evt.getClickCount() == 1) {      
                btnConceder.setEnabled(true);
        }    // TODO add your handling code here:
}//GEN-LAST:event_jTree1MouseClicked

private void tblUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuarioMouseClicked
  if (evt.getClickCount() == 1){
      jTree1.setEnabled(true);
      btnRetirar.setEnabled(true);
  
     }// TODO add your handling code here:
}//GEN-LAST:event_tblUsuarioMouseClicked

private void btnConcederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcederActionPerformed
   conceder();
   tblUsuario.setEnabled(false);
}//GEN-LAST:event_btnConcederActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ControleAcessosView1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConceder;
    private javax.swing.JButton btnRetirar;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTree jTree1;
    private java.util.List<sip.bean.NivelAcesso> nivelAcessoList;
    private javax.persistence.Query nivelAcessoQuery;
    private javax.swing.JTable tblConceder;
    private javax.swing.JTable tblInformacao;
    private javax.swing.JTable tblUsuario;
    private java.util.List<sip.bean.Usuario> usuarioList;
    private javax.persistence.Query usuarioQuery;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
